#!/usr/bin/env python3
import argparse,json,pathlib,re,sys
from repository import ROOT,GENERATED,dump,generated,topological
def load(n): return json.loads((GENERATED/f"{n}.json").read_text())
def main():
    ap=argparse.ArgumentParser(); ap.add_argument("--check",action="store_true"); a=ap.parse_args()
    deps=load("dependencies")["dependencies"]; reverse=load("reverse-dependencies")["reverse_dependencies"]; order=topological(deps)
    # Cross-check the root build declarations, which are independently maintained executable wiring.
    build=(ROOT/"build.zig").read_text()
    declared=set(re.findall(r'\.name = "([^"]+)"',build)); names=set(deps)
    if declared!=names: raise SystemExit(f"build/contract modules differ: build-only={sorted(declared-names)}, contract-only={sorted(names-declared)}")
    for name,ds in deps.items():
        block=re.search(rf'\.name = "{re.escape(name)}".*?\.dependencies = &\.\{{(.*?)\}}',build,re.S)
        wired=set(re.findall(r'"([^"]+)"',block.group(1))) if block else set()
        if wired!=set(ds): raise SystemExit(f"{name}: build dependencies {sorted(wired)} != contract {ds}")
    graphdir=GENERATED/"graphs"; reportdir=ROOT/"docs/reports/generated"; graphdir.mkdir(parents=True,exist_ok=True); reportdir.mkdir(parents=True,exist_ok=True)
    caps=load("capabilities")["capabilities"]; status=load("status")["status"]
    outs={
      graphdir/"module-dependencies.json":dump(generated({"edges":[{"module":m,"dependency":d} for m in sorted(deps) for d in deps[m]]})),
      graphdir/"reverse-dependencies.json":dump(generated({"reverse_dependencies":reverse})),
      graphdir/"porting-order.json":dump(generated({"order":order})),
      graphdir/"capability-to-module.json":dump(generated({"capabilities":caps})),
      graphdir/"maturity.json":dump(generated({"modules":status})),
      graphdir/"hyper-zig-readiness.json":dump(generated({"definition":"Contracted dependency closure; not a claim that a hypervisor is complete.","modules":order,"ready":False})),
      graphdir/"validation-status.json":dump(generated({"modules":status})),
    }
    edges=[(m,d) for m in sorted(deps) for d in deps[m]]
    outs[reportdir/"module-dependencies.mmd"]="%% Generated by tools/build-dependency-graphs.py; do not edit.\ngraph TD\n"+"".join(f'  {m.replace("-","_")} --> {d.replace("-","_")}\n' for m,d in edges)
    outs[reportdir/"module-dependencies.dot"]="// Generated by tools/build-dependency-graphs.py; do not edit.\ndigraph modules {\n"+"".join(f'  "{m}" -> "{d}";\n' for m,d in edges)+"}\n"
    outs[reportdir/"porting-order.mmd"]="%% Generated by tools/build-dependency-graphs.py; do not edit.\ngraph LR\n"+"".join(f'  n{i}["{n}"] --> n{i+1}["{order[i+1]}"]\n' for i,n in enumerate(order[:-1]))
    outs[reportdir/"hyper-zig-readiness.mmd"]="%% Generated by tools/build-dependency-graphs.py; do not edit.\ngraph TD\n  contracts[Contracted foundations] --> gaps[System integration gaps]\n  gaps --> proven[System proven: false]\n"
    stale=[]
    for p,c in outs.items():
        if a.check:
            if not p.exists() or p.read_text()!=c: stale.append(str(p.relative_to(ROOT)))
        else: p.write_text(c)
    if stale: print("stale graphs: "+", ".join(stale),file=sys.stderr); return 1
    print(f"{'checked' if a.check else 'generated'} {len(outs)} textual dependency graph views; graph is acyclic")
    return 0
if __name__=="__main__": raise SystemExit(main())
